import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import AosProvider from "../components/AosProvider";

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sora.variable} antialiased`}>
        <AosProvider />
        {children}
      </body>
    </html>
  );
}
